# Generated by Django 5.1.2 on 2024-11-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoViviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='ubicacion',
            field=models.CharField(default='España', max_length=100),
            preserve_default=False,
        ),
    ]
