# Generated by Django 5.1.2 on 2024-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoViviendas', '0002_vivienda_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='precioPorDia',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
