# Generated by Django 5.1.1 on 2024-11-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
        ('catalogoViviendas', '0002_alter_vivienda_imagen_alter_vivienda_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogoViviendas.vivienda'),
        ),
    ]
