name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonación completa para mejor relevancia del análisis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install coverage
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage xml
        working-directory: product/ProyectoWeb

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Jaime-Linares_PGPI-G3.10
            -Dsonar.organization=jaime-linares
            -Dsonar.python.coverage.reportPaths=product/ProyectoWeb/coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
